Update requirements.txt
Fixes initialization error caused with tensorflow (on my Mac) after
`from pactus import Dataset, featurizers`:

```
File /usr/local/anaconda3/lib/python3.8/site-packages/tensorflow/python/client/pywrap_tf_session.py:19, in <module>
     17 # pylint: disable=invalid-import-order,g-bad-import-order, wildcard-import, unused-import
     18 from tensorflow.python import pywrap_tensorflow
---> 19 from tensorflow.python.client._pywrap_tf_session import *
     20 from tensorflow.python.client._pywrap_tf_session import _TF_SetTarget
     21 from tensorflow.python.client._pywrap_tf_session import _TF_SetConfig

ImportError: initialization failed
```